import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { CustomFlowbiteTheme } from "flowbite-react";
import { Flowbite } from "flowbite-react";

const customTheme = {
  button: {
    color: {
      primary:"bg-indigo-500 text-white hover:bg-indigo-600",
      success:"bg-emerald-500 hover:bg-emerald-600 text-white",
      danger: "bg-red-500 hover:bg-red-600 text-white",
    },
  },
};

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "NCT Scheduling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SessionWrapper>
          <Flowbite theme={{ theme: customTheme }}>
            {children}
          </Flowbite>
        </SessionWrapper>
      </body>
    </html>
  );
}
